#pragma once
// Include this header in ScriptEngine.cpp to create the embedded module

#include "Atom/Scene/Components.h"
#include "Atom/Core/Input.h"
#include "Atom/Core/Timer.h"
#include "Atom/Physics/PhysicsEngine.h"

#include "Atom/Scripting/ScriptWrappers/Scene/EntityWrapper.h"
#include "Atom/Scripting/ScriptWrappers/Scene/ComponentWrapper.h"
#include "Atom/Scripting/ScriptWrappers/Math/MathWrapper.h"
#include "Atom/Scripting/ScriptWrappers/Renderer/MeshWrapper.h"
#include "Atom/Scripting/ScriptWrappers/Renderer/TextureWrapper.h"
#include "Atom/Scripting/ScriptWrappers/Renderer/MaterialWrapper.h"
#include "Atom/Scripting/ScriptWrappers/Renderer/AnimationWrapper.h"
#include "Atom/Scripting/ScriptWrappers/ImGui/ImGuiWrapper.h"

#include <glm/glm.hpp>
#include <pybind11/embed.h>
#include <pybind11/operators.h>
#include <pybind11/stl_bind.h>
#include <pybind11/stl/filesystem.h>

namespace Atom
{
    namespace py = pybind11;
    namespace wrappers = Atom::ScriptWrappers;

    PYBIND11_EMBEDDED_MODULE(Atom, m)
    {
        // --------------------------------------------------- Math ------------------------------------------------------------
        py::class_<glm::vec2>(m, "Vec2")
            .def(py::init<>())
            .def(py::init<f32>())
            .def(py::init<f32, f32>())
            .def(py::init<const glm::vec2&>())
            .def(py::self += py::self)
            .def(py::self -= py::self)
            .def(py::self *= py::self)
            .def(py::self /= py::self)
            .def(py::self + py::self)
            .def(py::self - py::self)
            .def(py::self * py::self)
            .def(py::self / py::self)
            .def(py::self += f32())
            .def(py::self -= f32())
            .def(py::self *= f32())
            .def(py::self /= f32())
            .def(py::self + f32())
            .def(py::self - f32())
            .def(py::self * f32())
            .def(py::self / f32())
            .def(-py::self)
            .def_readwrite("x", &glm::vec2::x)
            .def_readwrite("y", &glm::vec2::y);

        py::class_<glm::bvec2>(m, "BVec2")
            .def(py::init<>())
            .def(py::init<bool>())
            .def(py::init<bool, bool>())
            .def(py::init<const glm::bvec2&>())
            .def(py::self += py::self)
            .def(py::self -= py::self)
            .def(py::self *= py::self)
            .def(py::self /= py::self)
            .def(py::self + py::self)
            .def(py::self - py::self)
            .def(py::self * py::self)
            .def(py::self / py::self)
            .def(py::self += bool())
            .def(py::self -= bool())
            .def(py::self *= bool())
            .def(py::self /= bool())
            .def(py::self + bool())
            .def(py::self - bool())
            .def(py::self * bool())
            .def(py::self / bool())
            .def(-py::self)
            .def_readwrite("x", &glm::bvec2::x)
            .def_readwrite("y", &glm::bvec2::y);

        py::class_<glm::vec3>(m, "Vec3")
            .def(py::init<>())
            .def(py::init<f32>())
            .def(py::init<f32, f32, f32>())
            .def(py::init<const glm::vec3&>())
            .def(py::self += py::self)
            .def(py::self -= py::self)
            .def(py::self *= py::self)
            .def(py::self /= py::self)
            .def(py::self + py::self)
            .def(py::self - py::self)
            .def(py::self * py::self)
            .def(py::self / py::self)
            .def(py::self += f32())
            .def(py::self -= f32())
            .def(py::self *= f32())
            .def(py::self /= f32())
            .def(py::self + f32())
            .def(py::self - f32())
            .def(py::self * f32())
            .def(py::self / f32())
            .def(-py::self)
            .def_readwrite("x", &glm::vec3::x)
            .def_readwrite("y", &glm::vec3::y)
            .def_readwrite("z", &glm::vec3::z);

        py::class_<glm::bvec3>(m, "BVec3")
            .def(py::init<>())
            .def(py::init<bool>())
            .def(py::init<bool, bool, bool>())
            .def(py::init<const glm::bvec3&>())
            .def(py::self += py::self)
            .def(py::self -= py::self)
            .def(py::self *= py::self)
            .def(py::self /= py::self)
            .def(py::self + py::self)
            .def(py::self - py::self)
            .def(py::self * py::self)
            .def(py::self / py::self)
            .def(py::self += bool())
            .def(py::self -= bool())
            .def(py::self *= bool())
            .def(py::self /= bool())
            .def(py::self + bool())
            .def(py::self - bool())
            .def(py::self * bool())
            .def(py::self / bool())
            .def(-py::self)
            .def_readwrite("x", &glm::bvec3::x)
            .def_readwrite("y", &glm::bvec3::y)
            .def_readwrite("z", &glm::bvec3::z);

        py::class_<glm::vec4>(m, "Vec4")
            .def(py::init<>())
            .def(py::init<f32>())
            .def(py::init<f32, f32, f32, f32>())
            .def(py::init<const glm::vec4&>())
            .def(py::self += py::self)
            .def(py::self -= py::self)
            .def(py::self *= py::self)
            .def(py::self /= py::self)
            .def(py::self + py::self)
            .def(py::self - py::self)
            .def(py::self * py::self)
            .def(py::self / py::self)
            .def(py::self += f32())
            .def(py::self -= f32())
            .def(py::self *= f32())
            .def(py::self /= f32())
            .def(py::self + f32())
            .def(py::self - f32())
            .def(py::self * f32())
            .def(py::self / f32())
            .def(-py::self)
            .def_readwrite("x", &glm::vec4::x)
            .def_readwrite("y", &glm::vec4::y)
            .def_readwrite("z", &glm::vec4::z)
            .def_readwrite("w", &glm::vec4::y);

        py::class_<glm::bvec4>(m, "BVec4")
            .def(py::init<>())
            .def(py::init<bool>())
            .def(py::init<bool, bool, bool, bool>())
            .def(py::init<const glm::bvec4&>())
            .def(py::self += py::self)
            .def(py::self -= py::self)
            .def(py::self *= py::self)
            .def(py::self /= py::self)
            .def(py::self + py::self)
            .def(py::self - py::self)
            .def(py::self * py::self)
            .def(py::self / py::self)
            .def(py::self += bool())
            .def(py::self -= bool())
            .def(py::self *= bool())
            .def(py::self /= bool())
            .def(py::self + bool())
            .def(py::self - bool())
            .def(py::self * bool())
            .def(py::self / bool())
            .def(-py::self)
            .def_readwrite("x", &glm::bvec4::x)
            .def_readwrite("y", &glm::bvec4::y)
            .def_readwrite("z", &glm::bvec4::z)
            .def_readwrite("w", &glm::bvec4::y);

        py::class_<glm::quat>(m, "Quaternion")
            .def(py::init<>())
            .def(py::init<f32, f32, f32, f32>())
            .def(py::init<const glm::vec3&>())
            .def(py::self += py::self)
            .def(py::self -= py::self)
            .def(py::self *= py::self)
            .def(py::self + py::self)
            .def(py::self - py::self)
            .def(py::self * py::self)
            .def(-py::self)
            .def_readwrite("x", &glm::quat::x)
            .def_readwrite("y", &glm::quat::y)
            .def_readwrite("z", &glm::quat::z)
            .def_readwrite("w", &glm::quat::y);

        py::class_<wrappers::Math>(m, "Math")
            .def_static("abs", &wrappers::Math::Abs<f32>)
            .def_static("clamp", &wrappers::Math::Clamp<f32>)
            .def_static("ceil", &wrappers::Math::Ceil<f32>)
            .def_static("floor", &wrappers::Math::Floor<f32>)
            .def_static("max", &wrappers::Math::Max<f32>)
            .def_static("min", &wrappers::Math::Min<f32>)
            .def_static("mix", &wrappers::Math::Mix<f32>)
            .def_static("mix", &wrappers::Math::Mix<glm::vec2>)
            .def_static("mix", &wrappers::Math::Mix<glm::vec3>)
            .def_static("mix", &wrappers::Math::Mix<glm::vec4>)
            .def_static("round", &wrappers::Math::Round<f32>)
            .def_static("round_even", &wrappers::Math::RoundEven<f32>)
            .def_static("exp", &wrappers::Math::Exp<f32>)
            .def_static("exp2", &wrappers::Math::Exp2<f32>)
            .def_static("log", &wrappers::Math::Log<f32>)
            .def_static("log2", &wrappers::Math::Log2<f32>)
            .def_static("pow", &wrappers::Math::Pow<f32>)
            .def_static("sqrt", &wrappers::Math::Sqrt<f32>)
            .def_static("cross", &wrappers::Math::Cross)
            .def_static("dot", &wrappers::Math::Dot<glm::vec2>)
            .def_static("dot", &wrappers::Math::Dot<glm::vec3>)
            .def_static("dot", &wrappers::Math::Dot<glm::vec4>)
            .def_static("dot", &wrappers::Math::Dot<glm::quat>)
            .def_static("distance", &wrappers::Math::Distance<glm::vec2>)
            .def_static("distance", &wrappers::Math::Distance<glm::vec3>)
            .def_static("distance", &wrappers::Math::Distance<glm::vec4>)
            .def_static("length", &wrappers::Math::Length<glm::vec2>)
            .def_static("length", &wrappers::Math::Length<glm::vec3>)
            .def_static("length", &wrappers::Math::Length<glm::vec4>)
            .def_static("normalize", &wrappers::Math::Normalize<glm::vec2>)
            .def_static("normalize", &wrappers::Math::Normalize<glm::vec3>)
            .def_static("normalize", &wrappers::Math::Normalize<glm::vec4>)
            .def_static("normalize", &wrappers::Math::Normalize<glm::quat>)
            .def_static("reflect", &wrappers::Math::Reflect<glm::vec2>)
            .def_static("reflect", &wrappers::Math::Reflect<glm::vec3>)
            .def_static("reflect", &wrappers::Math::Reflect<glm::vec4>)
            .def_static("refract", &wrappers::Math::Refract<glm::vec2>)
            .def_static("refract", &wrappers::Math::Refract<glm::vec3>)
            .def_static("refract", &wrappers::Math::Refract<glm::vec4>)
            .def_static("perlin_noise", &wrappers::Math::PerlinNoise<glm::vec2>)
            .def_static("perlin_noise", &wrappers::Math::PerlinNoise<glm::vec3>)
            .def_static("perlin_noise", &wrappers::Math::PerlinNoise<glm::vec4>)
            .def_static("simplex_noise", &wrappers::Math::SimplexNoise<glm::vec2>)
            .def_static("simplex_noise", &wrappers::Math::SimplexNoise<glm::vec3>)
            .def_static("simplex_noise", &wrappers::Math::SimplexNoise<glm::vec4>)
            .def_static("acos", &wrappers::Math::Acos<f32>)
            .def_static("acosh", &wrappers::Math::Acosh<f32>)
            .def_static("asin", &wrappers::Math::Asin<f32>)
            .def_static("asinh", &wrappers::Math::Asinh<f32>)
            .def_static("atan", &wrappers::Math::Atan<f32>)
            .def_static("atanh", &wrappers::Math::Atanh<f32>)
            .def_static("sin", &wrappers::Math::Sin<f32>)
            .def_static("sinh", &wrappers::Math::Sinh<f32>)
            .def_static("cos", &wrappers::Math::Cos<f32>)
            .def_static("cosh", &wrappers::Math::Cosh<f32>)
            .def_static("tan", &wrappers::Math::Tan<f32>)
            .def_static("tanh", &wrappers::Math::Tanh<f32>)
            .def_static("degrees", &wrappers::Math::Degrees<f32>)
            .def_static("radians", &wrappers::Math::Radians<f32>)
            .def_static("lerp", &wrappers::Math::Lerp<f32>)
            .def_static("lerp", &wrappers::Math::Lerp<glm::vec2>)
            .def_static("lerp", &wrappers::Math::Lerp<glm::vec3>)
            .def_static("lerp", &wrappers::Math::Lerp<glm::vec4>)
            .def_static("lerp", &wrappers::Math::Lerp<glm::quat>)
            .def_static("euler_angles", &wrappers::Math::EulerAngles)
            .def_static("angle_axis", &wrappers::Math::AngleAxis)
            .def_static("inverse_quaternion", &wrappers::Math::InverseQuaternion);

        // --------------------------------------------------- Core ------------------------------------------------------------
        py::class_<Atom::Logger>(m, "Log")
            .def_static("trace", [](const char* message) { ATOM_TRACE(message); })
            .def_static("info", [](const char* message) { ATOM_INFO(message); })
            .def_static("warning", [](const char* message) { ATOM_WARNING(message); })
            .def_static("error", [](const char* message) { ATOM_ERROR(message); });

        py::enum_<Atom::Key>(m, "Key")
            .value("Backspace", Atom::Key::Backspace)
            .value("Tab", Atom::Key::Tab)
            .value("Clear", Atom::Key::Clear)
            .value("Enter", Atom::Key::Enter)
            .value("LShift", Atom::Key::LShift)
            .value("RShift", Atom::Key::RShift)
            .value("LCtrl", Atom::Key::LCtrl)
            .value("RCtrl", Atom::Key::RCtrl)
            .value("LAlt", Atom::Key::LAlt)
            .value("RAlt", Atom::Key::RAlt)
            .value("Pause", Atom::Key::Pause)
            .value("CapsLock", Atom::Key::CapsLock)
            .value("Esc", Atom::Key::Esc)
            .value("Space", Atom::Key::Space)
            .value("PageUp", Atom::Key::PageUp)
            .value("PageDown", Atom::Key::PageDown)
            .value("End", Atom::Key::End)
            .value("Home", Atom::Key::Home)
            .value("LeftArrow", Atom::Key::LeftArrow)
            .value("RightArrow", Atom::Key::RightArrow)
            .value("UpArrow", Atom::Key::UpArrow)
            .value("DownArrow", Atom::Key::DownArrow)
            .value("Select", Atom::Key::Select)
            .value("Print", Atom::Key::Print)
            .value("Execute", Atom::Key::Execute)
            .value("PrintScreen", Atom::Key::PrintScreen)
            .value("Ins", Atom::Key::Ins)
            .value("Del", Atom::Key::Del)
            .value("Help", Atom::Key::Help)
            .value("Key0", Atom::Key::Key0)
            .value("Key1", Atom::Key::Key1)
            .value("Key2", Atom::Key::Key2)
            .value("Key3", Atom::Key::Key3)
            .value("Key4", Atom::Key::Key4)
            .value("Key5", Atom::Key::Key5)
            .value("Key6", Atom::Key::Key6)
            .value("Key7", Atom::Key::Key7)
            .value("Key8", Atom::Key::Key8)
            .value("Key9", Atom::Key::Key9)
            .value("A", Atom::Key::A)
            .value("B", Atom::Key::B)
            .value("C", Atom::Key::C)
            .value("D", Atom::Key::D)
            .value("E", Atom::Key::E)
            .value("F", Atom::Key::F)
            .value("G", Atom::Key::G)
            .value("H", Atom::Key::H)
            .value("I", Atom::Key::I)
            .value("J", Atom::Key::J)
            .value("K", Atom::Key::K)
            .value("L", Atom::Key::L)
            .value("M", Atom::Key::M)
            .value("N", Atom::Key::N)
            .value("O", Atom::Key::O)
            .value("P", Atom::Key::P)
            .value("Q", Atom::Key::Q)
            .value("R", Atom::Key::R)
            .value("S", Atom::Key::S)
            .value("T", Atom::Key::T)
            .value("U", Atom::Key::U)
            .value("V", Atom::Key::V)
            .value("W", Atom::Key::W)
            .value("X", Atom::Key::X)
            .value("Y", Atom::Key::Y)
            .value("Z", Atom::Key::Z)
            .value("LWinKey", Atom::Key::LWinKey)
            .value("RWinKey", Atom::Key::RWinKey)
            .value("NumPad0", Atom::Key::NumPad0)
            .value("NumPad1", Atom::Key::NumPad1)
            .value("NumPad2", Atom::Key::NumPad2)
            .value("NumPad3", Atom::Key::NumPad3)
            .value("NumPad4", Atom::Key::NumPad4)
            .value("NumPad5", Atom::Key::NumPad5)
            .value("NumPad6", Atom::Key::NumPad6)
            .value("NumPad7", Atom::Key::NumPad7)
            .value("NumPad8", Atom::Key::NumPad8)
            .value("NumPad9", Atom::Key::NumPad9)
            .value("F1", Atom::Key::F1)
            .value("F2", Atom::Key::F2)
            .value("F3", Atom::Key::F3)
            .value("F4", Atom::Key::F4)
            .value("F5", Atom::Key::F5)
            .value("F6", Atom::Key::F6)
            .value("F7", Atom::Key::F7)
            .value("F8", Atom::Key::F8)
            .value("F9", Atom::Key::F9)
            .value("F10", Atom::Key::F10)
            .value("F11", Atom::Key::F11)
            .value("F12", Atom::Key::F12)
            .value("NumLock", Atom::Key::NumLock);

        py::enum_<Atom::MouseButton>(m, "MouseButton")
            .value("Left", Atom::MouseButton::Left)
            .value("Right", Atom::MouseButton::Right)
            .value("Middle", Atom::MouseButton::Middle)
            .value("X1", Atom::MouseButton::X1)
            .value("X2", Atom::MouseButton::X2);

        py::class_<Atom::Input>(m, "Input")
            .def_static("is_key_pressed", [](Atom::Key key) { return Atom::Input::IsKeyPressed(key); })
            .def_static("is_mouse_button_pressed", [](Atom::MouseButton button) { return Atom::Input::IsMouseButtonPressed(button); })
            .def_static("get_mouse_position", []() { return Atom::Input::GetMousePosition(); })
            .def_static("set_mouse_cursor", [](bool enabled) { Atom::Input::SetMouseCursor(enabled); })
            .def_static("set_mouse_position", [](const glm::vec2& position) { Atom::Input::SetMousePosition(position); })
            .def_static("is_cursor_enabled", []() { return Atom::Input::IsCursorEnabled(); });

        py::class_<Atom::Timestep>(m, "Timestep")
            .def(py::init<>())
            .def("get_seconds", &Atom::Timestep::GetSeconds)
            .def("get_milliseconds", &Atom::Timestep::GetMilliseconds);

        py::class_<Atom::Timer>(m, "Timer")
            .def(py::init<>())
            .def("reset", &Atom::Timer::Reset)
            .def("stop", &Atom::Timer::Stop)
            .def("get_elapsed_time", &Atom::Timer::GetElapsedTime);

        py::class_<Atom::Event>(m, "Event");

        py::class_<Atom::KeyEvent>(m, "KeyEvent");

        py::class_<Atom::MouseButtonEvent>(m, "MouseButtonEvent");

        py::class_<Atom::KeyPressedEvent, Atom::KeyEvent>(m, "KeyPressedEvent")
            .def(py::init<Atom::Key, s32>())
            .def_property_readonly("repeat_count", &Atom::KeyPressedEvent::GetRepeatCount)
            .def_property_readonly("key", &Atom::KeyEvent::GetKeyCode);

        py::class_<Atom::KeyReleasedEvent, Atom::KeyEvent>(m, "KeyReleasedEvent")
            .def(py::init<Atom::Key>())
            .def_property_readonly("key", &Atom::KeyEvent::GetKeyCode);

        py::class_<Atom::MouseButtonPressedEvent, Atom::MouseButtonEvent>(m, "MouseButtonPressedEvent")
            .def(py::init<Atom::MouseButton>())
            .def_property_readonly("mouse_button", &Atom::MouseButtonEvent::GetButton);

        py::class_<Atom::MouseButtonReleasedEvent, Atom::MouseButtonEvent>(m, "MouseButtonReleasedEvent")
            .def(py::init<Atom::MouseButton>())
            .def_property_readonly("mouse_button", &Atom::MouseButtonEvent::GetButton);

        py::class_<Atom::MouseMovedEvent, Atom::Event>(m, "MouseMovedEvent")
            .def(py::init<f32, f32>())
            .def_property_readonly("x", &Atom::MouseMovedEvent::GetXPosition)
            .def_property_readonly("y", &Atom::MouseMovedEvent::GetYPosition);

        py::class_<Atom::MouseScrolledEvent, Atom::Event>(m, "MouseScrolledEvent")
            .def(py::init<f32, f32>())
            .def_property_readonly("x_offset", &Atom::MouseScrolledEvent::GetXOffset)
            .def_property_readonly("y_offset", &Atom::MouseScrolledEvent::GetYOffset);

        // --------------------------------------------------- Scene ------------------------------------------------------------
        py::class_<Atom::SceneCamera>(m, "SceneCamera")
            .def(py::init<>())
            .def("set_viewport_size", &Atom::SceneCamera::SetViewportSize)
            .def_property("projection_type", &Atom::SceneCamera::GetProjectionType, &Atom::SceneCamera::SetProjectionType)
            .def_property("perspective_fov", &Atom::SceneCamera::GetPerspectiveFOV, &Atom::SceneCamera::SetPerspectiveFOV)
            .def_property("perspective_near", &Atom::SceneCamera::GetPerspectiveNear, &Atom::SceneCamera::SetPerspectiveNear)
            .def_property("perspective_far", &Atom::SceneCamera::GetPerspectiveFar, &Atom::SceneCamera::SetPerspectiveFar)
            .def_property("ortho_size", &Atom::SceneCamera::GetOrthographicSize, &Atom::SceneCamera::SetOrthographicSize)
            .def_property("ortho_near", &Atom::SceneCamera::GetOrthographicNear, &Atom::SceneCamera::SetOrthographicNear)
            .def_property("ortho_far", &Atom::SceneCamera::GetOrthographicFar, &Atom::SceneCamera::SetOrthographicFar);

        py::enum_<Atom::RigidbodyComponent::RigidbodyType>(m, "RigidbodyType")
            .value("Static", Atom::RigidbodyComponent::RigidbodyType::Static)
            .value("Dynamic", Atom::RigidbodyComponent::RigidbodyType::Dynamic);

        py::class_<wrappers::TransformComponent>(m, "TransformComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property_readonly("up_vector", &wrappers::TransformComponent::GetUpVector)
            .def_property_readonly("right_vector", &wrappers::TransformComponent::GetRightVector)
            .def_property_readonly("forward_vector", &wrappers::TransformComponent::GetForwardVector)
            .def_property("translation", &wrappers::TransformComponent::GetTranslation, &wrappers::TransformComponent::SetTranslation)
            .def_property("rotation", &wrappers::TransformComponent::GetRotation, &wrappers::TransformComponent::SetRotation)
            .def_property("euler_angles", &wrappers::TransformComponent::GetEulerAngles, &wrappers::TransformComponent::SetEulerAngles)
            .def_property("scale", &wrappers::TransformComponent::GetScale, &wrappers::TransformComponent::SetScale);

        py::class_<wrappers::CameraComponent>(m, "CameraComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("camera", &wrappers::CameraComponent::GetCamera, &wrappers::CameraComponent::SetCamera)
            .def_property("fixed_aspect_ratio", &wrappers::CameraComponent::GetFixedAspectRatio, &wrappers::CameraComponent::SetFixedAspectRatio)
            .def_property("is_primary_camera", &wrappers::CameraComponent::GetIsPrimaryCamera, &wrappers::CameraComponent::SetIsPrimaryCamera);

        py::class_<wrappers::MeshComponent>(m, "MeshComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("mesh", &wrappers::MeshComponent::GetMesh, &wrappers::MeshComponent::SetMesh);

        py::class_<wrappers::AnimatedMeshComponent>(m, "AnimatedMeshComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("mesh", &wrappers::AnimatedMeshComponent::GetMesh, &wrappers::AnimatedMeshComponent::SetMesh);

        py::class_<wrappers::AnimatorComponent>(m, "AnimatorComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("animation_controller", &wrappers::AnimatorComponent::GetAnimationController, &wrappers::AnimatorComponent::SetAnimationController)
            .def_property("current_time", &wrappers::AnimatorComponent::GetTime, &wrappers::AnimatorComponent::SetTime)
            .def_property("play", &wrappers::AnimatorComponent::GetPlay, &wrappers::AnimatorComponent::SetPlay);

        py::class_<wrappers::SkyLightComponent>(m, "SkyLightComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("environment_map", &wrappers::SkyLightComponent::GetEnvironmentMap, &wrappers::SkyLightComponent::SetEnvironmentMap);

        py::class_<wrappers::DirectionalLightComponent>(m, "DirectionalLightComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("color", &wrappers::DirectionalLightComponent::GetColor, &wrappers::DirectionalLightComponent::SetColor)
            .def_property("intensity", &wrappers::DirectionalLightComponent::GetIntensity, &wrappers::DirectionalLightComponent::SetIntensity);

        py::class_<wrappers::PointLightComponent>(m, "PointLightComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("color", &wrappers::PointLightComponent::GetColor, &wrappers::PointLightComponent::SetColor)
            .def_property("intensity", &wrappers::PointLightComponent::GetIntensity, &wrappers::PointLightComponent::SetIntensity)
            .def_property("attenuation_factors", &wrappers::PointLightComponent::GetAttenuation, &wrappers::PointLightComponent::SetAttenuation);

        py::class_<wrappers::SpotLightComponent>(m, "SpotLightComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("color", &wrappers::SpotLightComponent::GetColor, &wrappers::SpotLightComponent::SetColor)
            .def_property("intensity", &wrappers::SpotLightComponent::GetIntensity, &wrappers::SpotLightComponent::GetIntensity)
            .def_property("direction", &wrappers::SpotLightComponent::GetDirection, &wrappers::SpotLightComponent::GetDirection)
            .def_property("cone_angle", &wrappers::SpotLightComponent::GetConeAngle, &wrappers::SpotLightComponent::GetConeAngle)
            .def_property("attenuation_factors", &wrappers::SpotLightComponent::GetAttenuation, &wrappers::SpotLightComponent::SetAttenuation);

        py::class_<wrappers::RigidbodyComponent>(m, "RigidbodyComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def("add_force", &wrappers::RigidbodyComponent::AddForce)
            .def("add_impulse", &wrappers::RigidbodyComponent::AddImpulse)
            .def_property("type", &wrappers::RigidbodyComponent::GetType, &wrappers::RigidbodyComponent::SetType)
            .def_property("mass", &wrappers::RigidbodyComponent::GetMass, &wrappers::RigidbodyComponent::SetMass)
            .def_property("fixed_rotation", &wrappers::RigidbodyComponent::GetFixedRotation, &wrappers::RigidbodyComponent::SetFixedRotation)
            .def_property("velocity", &wrappers::RigidbodyComponent::GetVelocity, &wrappers::RigidbodyComponent::SetVelocity)
            .def_property("translation", &wrappers::RigidbodyComponent::GetTranslation, &wrappers::RigidbodyComponent::SetTranslation)
            .def_property("rotation", &wrappers::RigidbodyComponent::GetRotation, &wrappers::RigidbodyComponent::SetRotation)
            .def_property("euler_angles", &wrappers::RigidbodyComponent::GetEulerAngles, &wrappers::RigidbodyComponent::SetEulerAngles)
            .def_property_readonly("up_vector", &wrappers::RigidbodyComponent::GetUpVector)
            .def_property_readonly("right_vector", &wrappers::RigidbodyComponent::GetRightVector)
            .def_property_readonly("forward_vector", &wrappers::RigidbodyComponent::GetForwardVector);

        py::class_<wrappers::BoxColliderComponent>(m, "BoxColliderComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("center", &wrappers::BoxColliderComponent::GetCenter, &wrappers::BoxColliderComponent::SetCenter)
            .def_property("size", &wrappers::BoxColliderComponent::GetSize, &wrappers::BoxColliderComponent::SetSize)
            .def_property("restitution", &wrappers::BoxColliderComponent::GetRestitution, &wrappers::BoxColliderComponent::SetRestitution)
            .def_property("static_friction", &wrappers::BoxColliderComponent::GetStaticFriction, &wrappers::BoxColliderComponent::SetStaticFriction)
            .def_property("dynamic_friction", &wrappers::BoxColliderComponent::GetDynamicFriction, &wrappers::BoxColliderComponent::SetDynamicFriction);

        py::class_<wrappers::SphereColliderComponent>(m, "SphereColliderComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("center", &wrappers::SphereColliderComponent::GetCenter, &wrappers::SphereColliderComponent::SetCenter)
            .def_property("radius", &wrappers::SphereColliderComponent::GetRadius, &wrappers::SphereColliderComponent::GetRadius)
            .def_property("restitution", &wrappers::SphereColliderComponent::GetRestitution, &wrappers::SphereColliderComponent::SetRestitution)
            .def_property("static_friction", &wrappers::SphereColliderComponent::GetStaticFriction, &wrappers::SphereColliderComponent::SetStaticFriction)
            .def_property("dynamic_friction", &wrappers::SphereColliderComponent::GetDynamicFriction, &wrappers::SphereColliderComponent::SetDynamicFriction);

        py::class_<wrappers::CapsuleColliderComponent>(m, "CapsuleColliderComponent")
            .def(py::init<>())
            .def(py::init<wrappers::Entity>())
            .def_property_readonly("entity", &wrappers::Component::GetEntity)
            .def_property_readonly("is_valid", &wrappers::Component::IsValid)
            .def_property("center", &wrappers::CapsuleColliderComponent::GetCenter, &wrappers::CapsuleColliderComponent::SetCenter)
            .def_property("radius", &wrappers::CapsuleColliderComponent::GetRadius, &wrappers::CapsuleColliderComponent::SetRadius)
            .def_property("height", &wrappers::CapsuleColliderComponent::GetHeight, &wrappers::CapsuleColliderComponent::SetHeight)
            .def_property("restitution", &wrappers::CapsuleColliderComponent::GetRestitution, &wrappers::CapsuleColliderComponent::SetRestitution)
            .def_property("static_friction", &wrappers::CapsuleColliderComponent::GetStaticFriction, &wrappers::CapsuleColliderComponent::SetStaticFriction)
            .def_property("dynamic_friction", &wrappers::CapsuleColliderComponent::GetDynamicFriction, &wrappers::CapsuleColliderComponent::SetDynamicFriction);

        py::class_<wrappers::Entity>(m, "Entity")
            .def(py::init<>())
            .def(py::init<u64>())
            .def("add_camera_component", &wrappers::Entity::AddComponent<wrappers::CameraComponent>)
            .def("add_mesh_component", &wrappers::Entity::AddComponent<wrappers::MeshComponent>)
            .def("add_animated_mesh_component", &wrappers::Entity::AddComponent<wrappers::AnimatedMeshComponent>)
            .def("add_animator_component", &wrappers::Entity::AddComponent<wrappers::AnimatorComponent>)
            .def("add_sky_light_component", &wrappers::Entity::AddComponent<wrappers::SkyLightComponent>)
            .def("add_dir_light_component", &wrappers::Entity::AddComponent<wrappers::DirectionalLightComponent>)
            .def("add_point_light_component", &wrappers::Entity::AddComponent<wrappers::PointLightComponent>)
            .def("add_spot_light_component", &wrappers::Entity::AddComponent<wrappers::SpotLightComponent>)
            .def("add_rigidbody_component", &wrappers::Entity::AddComponent<wrappers::RigidbodyComponent>)
            .def("add_box_collider_component", &wrappers::Entity::AddComponent<wrappers::BoxColliderComponent>)
            .def("add_sphere_collider_component", &wrappers::Entity::AddComponent<wrappers::SphereColliderComponent>)
            .def("add_capsule_collider_component", &wrappers::Entity::AddComponent<wrappers::CapsuleColliderComponent>)
            .def("has_camera_component", &wrappers::Entity::HasComponent<wrappers::CameraComponent>)
            .def("has_mesh_component", &wrappers::Entity::HasComponent<wrappers::MeshComponent>)
            .def("has_animated_mesh_component", &wrappers::Entity::HasComponent<wrappers::AnimatedMeshComponent>)
            .def("has_animator_component", &wrappers::Entity::HasComponent<wrappers::AnimatorComponent>)
            .def("has_sky_light_component", &wrappers::Entity::HasComponent<wrappers::SkyLightComponent>)
            .def("has_dir_light_component", &wrappers::Entity::HasComponent<wrappers::DirectionalLightComponent>)
            .def("has_point_light_component", &wrappers::Entity::HasComponent<wrappers::PointLightComponent>)
            .def("has_spot_light_component", &wrappers::Entity::HasComponent<wrappers::SpotLightComponent>)
            .def("has_rigid_body_component", &wrappers::Entity::HasComponent<wrappers::RigidbodyComponent>)
            .def("has_box_collider_component", &wrappers::Entity::HasComponent<wrappers::BoxColliderComponent>)
            .def("has_sphere_collider_component", &wrappers::Entity::HasComponent<wrappers::SphereColliderComponent>)
            .def("has_capsule_collider_component", &wrappers::Entity::HasComponent<wrappers::CapsuleColliderComponent>)
            .def("get_camera_component", &wrappers::Entity::GetComponent<wrappers::CameraComponent>)
            .def("get_mesh_component", &wrappers::Entity::GetComponent<wrappers::MeshComponent>)
            .def("get_animated_mesh_component", &wrappers::Entity::GetComponent<wrappers::AnimatedMeshComponent>)
            .def("get_animator_component", &wrappers::Entity::GetComponent<wrappers::AnimatorComponent>)
            .def("get_sky_light_component", &wrappers::Entity::GetComponent<wrappers::SkyLightComponent>)
            .def("get_dir_light_component", &wrappers::Entity::GetComponent<wrappers::DirectionalLightComponent>)
            .def("get_point_light_component", &wrappers::Entity::GetComponent<wrappers::PointLightComponent>)
            .def("get_spot_light_component", &wrappers::Entity::GetComponent<wrappers::SpotLightComponent>)
            .def("get_rigidbody_component", &wrappers::Entity::GetComponent<wrappers::RigidbodyComponent>)
            .def("get_box_collider_component", &wrappers::Entity::GetComponent<wrappers::BoxColliderComponent>)
            .def("get_sphere_collider_component", &wrappers::Entity::GetComponent<wrappers::SphereColliderComponent>)
            .def("get_capsule_collider_component", &wrappers::Entity::GetComponent<wrappers::CapsuleColliderComponent>)
            .def("get_script", &wrappers::Entity::GetScriptInstance)
            .def("is_valid", &wrappers::Entity::IsValid)
            .def_static("find_entity_by_name", &wrappers::Entity::FindEntityByName)
            .def_static("create_entity", &wrappers::Entity::CreateEntity)
            .def_static("delete_entity", &wrappers::Entity::DeleteEntity)
            .def_property_readonly("id", &wrappers::Entity::GetUUID)
            .def_property_readonly("transform", &wrappers::Entity::GetComponent<wrappers::TransformComponent>)
            .def_property("tag", &wrappers::Entity::GetTag, &wrappers::Entity::SetTag);

        // --------------------------------------------------- Renderer ------------------------------------------------------------
        py::enum_<Atom::TextureFormat>(m, "TextureFormat")
            .value("R8", Atom::TextureFormat::R8)
            .value("RGBA8", Atom::TextureFormat::RGBA8)
            .value("RG16F", Atom::TextureFormat::RG16F)
            .value("RG32F", Atom::TextureFormat::RG32F)
            .value("RGBA16F", Atom::TextureFormat::RGBA16F)
            .value("RGBA32F", Atom::TextureFormat::RGBA32F);

        py::enum_<Atom::TextureFilter>(m, "TextureFilter")
            .value("Linear", Atom::TextureFilter::Linear)
            .value("Nearest", Atom::TextureFilter::Nearest)
            .value("Anisotropic", Atom::TextureFilter::Anisotropic);

        py::enum_<Atom::TextureWrap>(m, "TextureWrap")
            .value("Clamp", Atom::TextureWrap::Clamp)
            .value("Repeat", Atom::TextureWrap::Repeat);

        py::class_<wrappers::Texture>(m, "Texture")
            .def("update_gpu_data", &wrappers::Texture2D::UpdateGPUData)
            .def_property_readonly("format", &wrappers::Texture::GetFormat)
            .def_property_readonly("width", &wrappers::Texture::GetWidth)
            .def_property_readonly("height", &wrappers::Texture::GetHeight)
            .def_property_readonly("depth", &wrappers::Texture::GetDepth)
            .def_property_readonly("array_size", &wrappers::Texture::GetArraySize)
            .def_property_readonly("mip_levels", &wrappers::Texture::GetMipLevels)
            .def_property_readonly("is_cpu_readable", &wrappers::Texture::IsCpuReadable)
            .def_property_readonly("is_gpu_writable", &wrappers::Texture::IsGpuWritable)
            .def_property("filter", &wrappers::Texture::GetFilter, &wrappers::Texture::SetFilter)
            .def_property("wrap", &wrappers::Texture::GetWrap, &wrappers::Texture::SetWrap);

        py::class_<wrappers::Texture2D>(m, "Texture2D")
            .def(py::init<u32, u32, Atom::TextureFormat, u32, bool, bool>())
            .def(py::init<u64>())
            .def("set_pixels", &wrappers::Texture2D::SetPixels)
            .def("get_pixels", &wrappers::Texture2D::GetPixels)
            .def_static("find", &wrappers::Texture2D::Find);

        py::class_<wrappers::TextureCube>(m, "TextureCube")
            .def(py::init<u32, Atom::TextureFormat, u32, bool, bool>())
            .def(py::init<u64>())
            .def("set_pixels", &wrappers::TextureCube::SetPixels)
            .def("get_pixels", &wrappers::TextureCube::GetPixels)
            .def_static("find", &wrappers::TextureCube::Find);

        py::enum_<Atom::MaterialFlags>(m, "MaterialFlags")
            .value("DepthTested", Atom::MaterialFlags::DepthTested)
            .value("Wireframe", Atom::MaterialFlags::Wireframe)
            .value("TwoSided", Atom::MaterialFlags::TwoSided)
            .value("Transparent", Atom::MaterialFlags::Transparent);

        py::class_<wrappers::Material>(m, "Material")
            .def(py::init<>())
            .def(py::init<u64>())
            .def("set_int", &wrappers::Material::SetInt)
            .def("set_float", &wrappers::Material::SetFloat)
            .def("set_vec2", &wrappers::Material::SetVec2)
            .def("set_vec3", &wrappers::Material::SetVec3)
            .def("set_vec4", &wrappers::Material::SetVec4)
            .def("set_texture", &wrappers::Material::SetTexture)
            .def("set_flag", &wrappers::Material::SetFlag)
            .def("get_int", &wrappers::Material::GetInt)
            .def("get_float", &wrappers::Material::GetFloat)
            .def("get_vec2", &wrappers::Material::GetVec2)
            .def("get_vec3", &wrappers::Material::GetVec3)
            .def("get_vec4", &wrappers::Material::GetVec4)
            .def("get_texture", &wrappers::Material::GetTexture)
            .def("has_int", &wrappers::Material::HasInt)
            .def("has_float", &wrappers::Material::HasFloat)
            .def("has_vec2", &wrappers::Material::HasVec2)
            .def("has_vec3", &wrappers::Material::HasVec3)
            .def("has_vec4", &wrappers::Material::HasVec4)
            .def("has_texture", &wrappers::Material::HasTexture)
            .def("has_flag", &wrappers::Material::HasFlag)
            .def_static("find", &wrappers::Material::Find);

        py::class_<Atom::Submesh>(m, "Submesh")
            .def(py::init<>())
            .def_readwrite("start_vertex", &Atom::Submesh::StartVertex)
            .def_readwrite("vertex_count", &Atom::Submesh::VertexCount)
            .def_readwrite("start_index", &Atom::Submesh::StartIndex)
            .def_readwrite("index_count", &Atom::Submesh::IndexCount)
            .def_readwrite("material_index", &Atom::Submesh::MaterialIndex);

        py::class_<wrappers::Mesh>(m, "Mesh")
            .def(py::init<>())
            .def(py::init<u64>())
            .def("update_gpu_data", &wrappers::Mesh::UpdateGPUData)
            .def("set_material", &wrappers::Mesh::SetMaterial)
            .def("get_material", &wrappers::Mesh::GetMaterial)
            .def("set_positions", py::overload_cast<const py::list&>(&wrappers::Mesh::SetPositions))
            .def("set_uvs", py::overload_cast<const py::list&>(&wrappers::Mesh::SetUVs))
            .def("set_normals", py::overload_cast<const py::list&>(&wrappers::Mesh::SetNormals))
            .def("set_tangents", py::overload_cast<const py::list&>(&wrappers::Mesh::SetTangents))
            .def("set_bitangents", py::overload_cast<const py::list&>(&wrappers::Mesh::SetBitangents))
            .def("set_indices", py::overload_cast<const py::list&>(&wrappers::Mesh::SetIndices))
            .def("set_submeshes", py::overload_cast<const py::list&>(&wrappers::Mesh::SetSubmeshes))
            .def_static("find", &wrappers::Mesh::Find)
            .def_property_readonly("is_readable", &wrappers::Mesh::IsReadable)
            .def_property_readonly("is_empty", &wrappers::Mesh::IsEmpty)
            .def_property_readonly("positions", &wrappers::Mesh::GetPositions)
            .def_property_readonly("uvs", &wrappers::Mesh::GetUVs)
            .def_property_readonly("normals", &wrappers::Mesh::GetNormals)
            .def_property_readonly("tangents", &wrappers::Mesh::GetTangents)
            .def_property_readonly("bitangents", &wrappers::Mesh::GetBitangents)
            .def_property_readonly("indices", &wrappers::Mesh::GetIndices)
            .def_property_readonly("submeshes", &wrappers::Mesh::GetSubmeshes);

        py::class_<wrappers::Animation>(m, "Animation")
            .def(py::init<u64>())
            .def_static("find", &wrappers::Animation::Find)
            .def_property_readonly("duration", &wrappers::Animation::GetDuration)
            .def_property_readonly("ticks_per_second", &wrappers::Animation::GetTicksPerSecond);

        py::class_<wrappers::AnimationController>(m, "AnimationController")
            .def(py::init<u64>())
            .def_static("find", &wrappers::AnimationController::Find)
            .def("transition_to_state", &wrappers::AnimationController::TransitionToState)
            .def_property_readonly("current_state", &wrappers::AnimationController::GetCurrentState)
            .def_property_readonly("initial_state", &wrappers::AnimationController::GetInitialState)
            .def_property_readonly("animation_states", &wrappers::AnimationController::GetAnimationStates);

        // --------------------------------------------------- ImGui ------------------------------------------------------------
        py::class_<wrappers::GUI>(m, "GUI")
            .def_static("same_line", &wrappers::GUI::SameLine)
            .def_static("get_window_size", &wrappers::GUI::GetWindowSize)
            .def_static("get_window_position", &wrappers::GUI::GetWindowPosition)
            .def_static("begin_drag_drop_source", &wrappers::GUI::BeginDragDropSource)
            .def_static("end_drag_drop_source", &wrappers::GUI::EndDragDropSource)
            .def_static("begin_drag_drop_target", &wrappers::GUI::BeginDragDropTarget)
            .def_static("end_drag_drop_target", &wrappers::GUI::EndDragDropTarget)
            .def_static("set_drag_drop_payload", &wrappers::GUI::SetDragDropPayload)
            .def_static("get_drag_drop_payload", &wrappers::GUI::GetDragDropPayload)
            .def_static("get_window_position", &wrappers::GUI::GetWindowPosition)
            .def_static("get_window_position", &wrappers::GUI::GetWindowPosition)
            .def_static("text", py::overload_cast<const String&>(&wrappers::GUI::Text))
            .def_static("text", py::overload_cast<const String&, const glm::vec2&>(&wrappers::GUI::Text))
            .def_static("button", py::overload_cast<const String&, const glm::vec2&>(&wrappers::GUI::Button))
            .def_static("button", py::overload_cast<const String&, const glm::vec2&, const glm::vec2&>(&wrappers::GUI::Button))
            .def_static("image_button", py::overload_cast<wrappers::Texture2D, const glm::vec2&, const glm::vec2&, const glm::vec2&>(&wrappers::GUI::ImageButton))
            .def_static("image_button", py::overload_cast<wrappers::Texture2D, const glm::vec2&, const glm::vec2&, const glm::vec2&, const glm::vec2&>(&wrappers::GUI::ImageButton))
            .def_static("image", py::overload_cast<wrappers::Texture2D, const glm::vec2&, const glm::vec2&, const glm::vec2&>(&wrappers::GUI::Image))
            .def_static("image", py::overload_cast<wrappers::Texture2D, const glm::vec2&, const glm::vec2&, const glm::vec2&, const glm::vec2&>(&wrappers::GUI::Image))
            .def_static("begin_child_window", &wrappers::GUI::BeginChildWindow)
            .def_static("end_child_window", &wrappers::GUI::EndChildWindow);

        // --------------------------------------------------- Physics ------------------------------------------------------------
        py::class_<Atom::RaycastHitResult>(m, "RaycastHitResult")
            .def(py::init<>())
            .def_readwrite("is_valid", &Atom::RaycastHitResult::IsValid)
            .def_readwrite("position", &Atom::RaycastHitResult::Position)
            .def_readwrite("normal", &Atom::RaycastHitResult::Normal)
            .def_readwrite("uv", &Atom::RaycastHitResult::UV)
            .def_readwrite("face_index", &Atom::RaycastHitResult::FaceIndex)
            .def_readwrite("distance", &Atom::RaycastHitResult::Distance);

        py::class_<Atom::PhysicsEngine>(m, "Physics")
            .def_static("ray_cast", &Atom::PhysicsEngine::RayCast)
            .def_static("sphere_cast", &Atom::PhysicsEngine::SphereCast)
            .def_static("box_cast", &Atom::PhysicsEngine::BoxCast);
    }
}